### ISSUE TITLE
JS error when adding more values to a fieldgroup that contains textarea fields

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#857]
Here is a video of problem:
https://www.youtube.com/watch?v=HCxfIMP39BI

When I click here:
![Image of Bug](https://i.imgur.com/GmBJITQ.png)
it seems to create the following error
```
Uncaught TypeError: Cannot read property 'options' of undefined
    at addField186 (index.php?option=com_flexicontent&task=items.edit&view=item&id=741:4241)
    at addField148 (index.php?option=com_flexicontent&task=items.edit&view=item&id=741:4699)
    at HTMLSpanElement.onclick (index.php?option=com_flexicontent&task=items.edit&view=item&id=741:6486)
```

It was fine with 3.2.1.12 - but since FLEXIcontent 3.2.1.13 appeared.

**Comment by ggppdk** [comment]
On quick test i can not replicate
maybe it depends on configuration of used fields in the fieldgroup

Please contact me with PM in our forums as i may need more information

**Comment by ggppdk** [comment]
Please contact me with more information at our forums 
this may depend on specific field type (e.g. image-galler field) with specific configuration

**Comment by iamrobert** [comment]
Thanks - I have sent a PM to you on FLEXIcontent.

**Comment by ggppdk** [comment]
The problem is with duplicating a textarea with CodeMirror
and occurs while trying to get the CodeMirror options

will make a fix

**Comment by ggppdk** [comment]
Actually the issue effected all fields having textarea with HTML editor
Fixed it with 025f580

**Comment by iamrobert** [comment]
Thanks - it solves the issue.

I am still getting a js error missing:

`/media/editors/codemirror/mode/text/html/text/html.min.js 
`

Its being called from:
`/media/editors/codemirror/lib/addons.min.js`

Here I guess:
`a.modeURL||(a.modeURL="../mode/%N/%N.js");`

But there isn't a mode called either: html or text or a file called html.min.js

https://github.com/joomla/joomla-cms/tree/staging/media/editors/codemirror/mode

Maybe it should be htmlmixed:
https://github.com/joomla/joomla-cms/tree/staging/media/editors/codemirror/mode/htmlmixed
